CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  admin BOOLEAN default FALSE,
  user_name TEXT not null,
  full_name TEXT not null,
  date_created TIMESTAMP DEFAULT now() NOT NULL,
  date_modified TIMESTAMP DEFAULT null,
  password TEXT NOT NULL
);

