CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  admin BOOLEAN default FALSE,
  user_name TEXT not null,
  full_name TEXT not null,
  date_created TIMESTAMP NOT NULL DEFAULT now(),
  date_modified TIMESTAMP,
  password TEXT NOT NULL
);

