CREATE TABLE IF NOT EXISTS comments (
  comment_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id INTEGER REFERENCES users(id) NOT NULL,
  content TEXT NOT NULL,
  date_created TIMESTAMP NOT NULL default now(),
  date_modified TIMESTAMP
);